version: '3.8'

services:
  dan-agent:
    container_name: dan-browser-agent
    platform: linux/amd64
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile}
      args:
        TARGETPLATFORM: ${TARGETPLATFORM:-linux/amd64}
    ports:
      - "10000:10000"   # FastAPI
      - "7788:7788"     # Gradio / browser-use
      - "6080:6080"     # noVNC UI
      - "5901:5901"     # VNC Server
      - "9222:9222"     # Chrome Dev Tools
    environment:
      # === API KEYS / ENDPOINTS ===
      - OPENAI_ENDPOINT=${OPENAI_ENDPOINT:-https://api.openai.com/v1}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT:-}
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY:-}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY:-}
      - HUGGINGFACE_TOKEN=${HUGGINGFACE_TOKEN:-}
      - LLM_MODEL_NAME=${LLM_MODEL_NAME:-mistralai/Mistral-7B-Instruct-v0.1}

      # === browser-use / playwright ===
      - BROWSER_USE_LOGGING_LEVEL=info
      - ANONYMIZED_TELEMETRY=false
      - DISPLAY=:99
      - CHROME_PATH=/mnt/data/ms-playwright/chromium-*/chrome-linux/chrome
      - CHROME_USER_DATA=/app/data/chrome_data
      - CHROME_CDP=http://localhost:9222
      - CHROME_DEBUGGING_PORT=9222
      - CHROME_DEBUGGING_HOST=localhost
      - CHROME_PERSISTENT_SESSION=true
      - PLAYWRIGHT_BROWSERS_PATH=/mnt/data/ms-playwright

      # === Tela e VNC ===
      - VNC_PASSWORD=${VNC_PASSWORD:-vncpassword}
      - RESOLUTION=1920x1080x24
      - RESOLUTION_WIDTH=1920
      - RESOLUTION_HEIGHT=1080
      - PORT=10000

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./data:/app/data
      - ./logs:/var/log/supervisor
      - ./public_yaml:/home/carlos/public_yaml
    restart: unless-stopped
    shm_size: '2gb'
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp=unconfined
    tmpfs:
      - /tmp
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "5901"]
      interval: 10s
      timeout: 5s
      retries: 3
